name: RPGSprint
version: '${project.version}'
main: me.lojosho.rpgsprint.RPGSprint
api-version: 1.18
authors: [ LoJoSho ]
depend:
  - PlaceholderAPI
commands:
  RPGSprint:
    description: Default commands for interacting with RPGSprint